eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/
server:
  port: 8789
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:8787
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
