#server:
#  port: 8778
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig
          searchPaths: respo
          username:
          password:
      label: master
  application:
    name: eureka-config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/