eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/
server:
  port: 8784
spring:
  application:
    name: zipkin-server
  sleuth:
    sampler:
    percentage: 1.0
    enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: xavier
zipkin:
  storage:
    type: mysql