eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8773
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
      #      url: http://localhost:8762  #if you use URL instead of serviceId, Zuul will visit this exact URL directly. This is not recommended.
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
#zuul.prefix: /v1  #with this prefix, all url should be placed this prefix - localhost:8773/v1/hiapi/hi?name=tatze