eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/
server:
  port: 8788
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:8787
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service